server:
  port: 9000
spring:
  application:
    name: balawo-gateway
  redis:
    database: 0
    host: localhost #加入哨兵后，此项可以不配置
    port: 6379
    password:  # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  security:
    user:
      name: demo
      password: 123
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: false #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          lower-case-service-id: true #是否将服务id转换为小写
      routes:
        - id: payment_routh #配置路由ID,没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001 #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/demo1/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1

        - id: balawo_oauth_routh #配置路由ID,没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9002 #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/demo2/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1
      globalcors: #统一配置跨域请求,所有请求通过
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3628800